[package]
name = "samd21-usb-defmt"
version = "0.1.0"
edition = "2021"
resolver = "2"

[package.metadata]
chip = "ATSAMD21G18A"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7", optional = true }

atsamd-hal = { version = "0.23.3", default-features = false}

usb-device = { version ="0.3.2", optional = true }
usbd-serial ={ version = "0.2.2", optional = true }

defmt = { version = "1.1.0"}
portable-atomic = { version = "1.13.1", features = ["critical-section"] }
embassy-executor = { version = "0.10.0", features = ["defmt", "executor-thread", "platform-cortex-m"] }
embassy-time = { version = "0.5.1", features = ["defmt", "tick-hz-1_000"] }
critical-section = "1.2.0"
embassy-time-driver = "0.2.2"
bmp390-rs = "0.4.0"

[features]
default = ["rt", "usb", "atsamd-hal/samd21g"]
rt = ["dep:cortex-m-rt", "atsamd-hal/samd21g-rt"]
usb = ["atsamd-hal/usb", "dep:usb-device", "dep:usbd-serial",]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = false
debug = true
